PackageIdentifier: AgileBits.1Password.CLI
PackageVersion: 2.21.0
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: ./op.exe
    PortableCommandAlias: op
Commands:
  - op
Installers:
  - Architecture: x86
    InstallerUrl: https://cache.agilebits.com/dist/1P/op2/pkg/v2.21.0/op_windows_386_v2.21.0.zip
    InstallerSha256: bb617e24ce88b2aa5e0ab7a98b86704da6c8a72bda2cf7a55cc0237787d160dc
  - Architecture: x64
    InstallerUrl: https://cache.agilebits.com/dist/1P/op2/pkg/v2.21.0/op_windows_amd64_v2.21.0.zip
    InstallerSha256: b4101dc0697486d7bb79a5467a02dc4ee18f3cac77170ad1ba6670e2b3d339ae
ManifestType: installer
ManifestVersion: 1.5.0
