PackageIdentifier: AgileBits.1Password.CLI
PackageVersion: 2.30.0
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: ./op.exe
    PortableCommandAlias: op
Commands:
  - op
Installers:
  - Architecture: x86
    InstallerUrl: https://cache.agilebits.com/dist/1P/op2/pkg/v2.30.0/op_windows_386_v2.30.0.zip
    InstallerSha256: c01638037abccc0746d0db73f3a24f9d9afe2cb81403fb10b195976a25cbc576
  - Architecture: x64
    InstallerUrl: https://cache.agilebits.com/dist/1P/op2/pkg/v2.30.0/op_windows_amd64_v2.30.0.zip
    InstallerSha256: c01638037abccc0746d0db73f3a24f9d9afe2cb81403fb10b195976a25cbc576
ManifestType: installer
ManifestVersion: 1.5.0
